### ISSUE TITLE
loading IR files in Jalv sometimes fails

### ISSUE THREAD

**Issue by loki42** [x42/convoLV2#7]
Loading IRs in Jalv sometimes fails. The filename appears to be corrupt, with random characters from previous files names following the file name. I'm not sure if the error is similar in other hosts but sometimes and IR will fail to load but later load fine, which is suggesting some kind of memory corruption to me.

**Comment by x42** [comment]
I don't have an immediate explanation, and in a quick test cannot reproduce it, but I'll look into it.

What distro do you use? Which version of jalv?

**Comment by loki42** [comment]
Ubuntu 18.04.2 LTS
Jalv.gtk,  latest from git.

**Comment by x42** [comment]
Some notes to self: 

It may be that the data passed to the worker-thread is not properly terminated, and it mostly works because of padding? or the path isn't properly zero-terminated in modern jalv, and the plugin would have to check LV2Atom::size?

https://github.com/x42/convoLV2/blob/d2f102b7aa39056285ef995c958fc0957a612b72/lv2.c#L408

**Comment by loki42** [comment]
Changing directories seems to fix or make it more likely. I did
contemplating scanning right for the first .wav as it's always extra
trailing characters but that's just a dodgy work around.

**Comment by x42** [comment]
It likely was a recent jalv bug: https://github.com/drobilla/jalv/issues/32
That would also explain why I have not been able to reproduce it here.

**Comment by x42** [comment]
I'll see if I can work around this in convo.lv2
